services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: livechat_app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    depends_on:
      - mysql
      - redis
    networks:
      - livechat

  nginx:
    image: nginx:latest
    container_name: livechat_nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - livechat

  mysql:
    image: mysql:8.4
    container_name: livechat_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: livechat
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: livechat
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - livechat

  redis:
    image: redis:7
    container_name: livechat_redis
    ports:
      - "6379:6379"
    networks:
      - livechat

  soketi:
    image: local/soketi:latest
    container_name: livechat_soketi
    environment:
      SOKETI_DEBUG: 1
      SOKETI_DEFAULT_APP_ID: livechat
      SOKETI_DEFAULT_APP_KEY: appkey
      SOKETI_DEFAULT_APP_SECRET: appsecret
    ports:
      - "6001:6001"
    networks:
      - livechat

  horizon:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: livechat_horizon
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    depends_on:
      - redis
      - mysql
    command: php artisan horizon
    networks:
      - livechat

  scheduler:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: livechat_scheduler
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    depends_on:
      - mysql
      - redis
    command: sh -c "while true; do php artisan schedule:run --verbose --no-interaction; sleep 60; done"
    networks:
      - livechat

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: livechat_phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - livechat
networks:
  livechat:

volumes:
  mysql_data:




# version: "3.9"

# services:

#   app:
#     build:
#       context: .
#       dockerfile: docker/php/Dockerfile
#     container_name: livechat_app
#     working_dir: /var/www
#     volumes:
#       - ./src:/var/www
#     depends_on:
#       - mysql
#       - redis
#     networks:
#       - livechat

#   nginx:
#     image: nginx:latest
#     container_name: livechat_nginx
#     ports:
#       - "8000:80"
#     volumes:
#       - ./src:/var/www
#       - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
#     depends_on:
#       - app
#     networks:
#       - livechat

#   queue:
#     build:
#       context: .
#       dockerfile: docker/php/Dockerfile
#     container_name: livechat_queue
#     working_dir: /var/www
#     command: php artisan horizon
#     volumes:
#       - ./src:/var/www
#     depends_on:
#       - redis
#       - mysql
#     networks:
#       - livechat

#   mysql:
#     image: mysql:8.4
#     container_name: livechat_mysql
#     restart: unless-stopped
#     environment:
#       MYSQL_DATABASE: livechat
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_USER: livechat
#       MYSQL_PASSWORD: secret
#     ports:
#       - "3307:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql
#     networks:
#       - livechat

#   redis:
#     image: redis:7
#     container_name: livechat_redis
#     ports:
#       - "6379:6379"
#     networks:
#       - livechat

#   soketi:
#     image: local/soketi:latest
#     container_name: livechat_soketi
#     environment:
#       SOKETI_DEBUG: 1
#       SOKETI_DEFAULT_APP_ID: livechat
#       SOKETI_DEFAULT_APP_KEY: appkey
#       SOKETI_DEFAULT_APP_SECRET: appsecret
#     ports:
#       - "6001:6001"
#     networks:
#       - livechat

# networks:
#   livechat:

# volumes:
#   mysql_data: